blank_issues_enabled: true
contact_links:
  - name: Moja global Slack Community.
    url: https://join.slack.com/t/mojaglobal/shared_invite/zt-o6ta1ug0-rVLjAo460~d7JbZ~HpFFtw
    about: Talk to us about moja global and ask general questions.
  - name: Moja global documentation
    url: https://docs.moja.global/en/latest/
    about:  Technical Documentation for moja global.
  - name: moja global's community website
    url: https://community.moja.global/
    about: Learn about moja global's projects and the community.
