blank_issues_enabled: true
contact_links:
  - name: moja global Slack chat.
    url: https://join.slack.com/t/mojaglobal/shared_invite/zt-o6ta1ug0-rVLjAo460~d7JbZ~HpFFtw
    about: Chat to us about moja global and ask general questions.